schema_version = "1.0.0"

id = "best_presets"
version = "0.5.3"
name = "Best Presets"
tagline = "Quick preset tools for Blender"
maintainer = "Jan-Hendrik Müller"
type = "add-on"

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Geometry Nodes"]

blender_version_min = "5.1.0"

# https://spdx.org/licenses/
license = [
  "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/dist/",
  "/*.zip",
  "/*.dmg",
]
